# Generated by Django 3.1.4 on 2022-06-10 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(default='', max_length=8, verbose_name='社團名稱')),
                ('now_num', models.CharField(default='', max_length=8, verbose_name='目前人數')),
                ('max_num', models.CharField(default='', max_length=8, verbose_name='上限人數')),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_club', to=settings.AUTH_USER_MODEL)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_club', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(default='', max_length=8, verbose_name='學生姓名')),
                ('stu_grade', models.IntegerField(choices=[(0, '高一'), (1, '高二')], default=0, verbose_name='年級')),
                ('stu_class', models.IntegerField(choices=[(0, '1'), (1, '2'), (2, '3'), (3, '4'), (4, '5'), (5, '6'), (6, '7'), (7, '8'), (8, '9'), (9, '10')], default=0, verbose_name='學生班級')),
                ('stu_num', models.CharField(default='', max_length=8, verbose_name='座號')),
                ('ori_club', models.IntegerField(choices=[(0, '資訊社'), (1, '籃球社'), (2, '羽球社'), (3, '桌遊社'), (4, '吉他社')], default=0, verbose_name='原社團')),
                ('new_club', models.IntegerField(choices=[(0, '資訊社'), (1, '籃球社'), (2, '羽球社'), (3, '桌遊社'), (4, '吉他社')], default=0, verbose_name='欲轉社社團')),
                ('Yes_or_No_od', models.IntegerField(choices=[(0, '未答覆'), (1, '同意'), (2, '不同意')], default=0, verbose_name='原社團社長')),
                ('Yes_or_No_ot', models.IntegerField(choices=[(0, '未答覆'), (1, '同意'), (2, '不同意')], default=0, verbose_name='原社團指導老師')),
                ('Yes_or_No_nd', models.IntegerField(choices=[(0, '未答覆'), (1, '同意'), (2, '不同意')], default=0, verbose_name='新社團社長')),
                ('Yes_or_No_nt', models.IntegerField(choices=[(0, '未答覆'), (1, '同意'), (2, '不同意')], default=0, verbose_name='新社團指導老師')),
                ('Yes_or_No_final', models.IntegerField(choices=[(0, '未答覆'), (1, '同意'), (2, '不同意')], default=0, verbose_name='教務處審核')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='備註')),
            ],
        ),
        migrations.CreateModel(
            name='TransferForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(verbose_name='申請時間')),
                ('approve_od', models.IntegerField(choices=[(0, '未答覆'), (1, '同意'), (2, '不同意')], default=0, verbose_name='原社團社長審核')),
                ('approve_oa', models.IntegerField(choices=[(0, '未答覆'), (1, '同意'), (2, '不同意')], default=0, verbose_name='原社團指導老師審核')),
                ('approve_nd', models.IntegerField(choices=[(0, '未答覆'), (1, '同意'), (2, '不同意')], default=0, verbose_name='新社團社長審核')),
                ('approve_na', models.IntegerField(choices=[(0, '未答覆'), (1, '同意'), (2, '不同意')], default=0, verbose_name='新社團指導老師審核')),
                ('approve_st', models.IntegerField(choices=[(0, '未答覆'), (1, '同意'), (2, '不同意')], default=0, verbose_name='行政單位審核')),
                ('club_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_form', to='log.clubitem')),
                ('club_orig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_form', to='log.clubitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
