# Generated by Django 3.1.4 on 2022-06-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=8, verbose_name='社長')),
                ('teacher', models.CharField(max_length=8, verbose_name='指導老師')),
                ('now_num', models.CharField(max_length=8, verbose_name='目前人數')),
                ('max_num', models.CharField(max_length=8, verbose_name='上限人數')),
            ],
        ),
        migrations.CreateModel(
            name='FormItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=8, verbose_name='學生姓名')),
                ('stu_grade', models.IntegerField(choices=[(0, '高一'), (1, '高二')], default=0, verbose_name='年級')),
                ('stu_class', models.IntegerField(choices=[(0, '1'), (1, '2'), (2, '3'), (3, '4'), (4, '5'), (5, '6'), (6, '7'), (7, '8'), (8, '9'), (9, '10')], default=0, verbose_name='學生班級')),
                ('stu_num', models.CharField(max_length=8, verbose_name='座號')),
                ('ori_club', models.IntegerField(choices=[(0, '資訊社'), (1, '籃球社'), (2, '羽球社'), (3, '桌遊社'), (4, '吉他社')], default=0, verbose_name='原社團')),
                ('new_club', models.IntegerField(choices=[(0, '資訊社'), (1, '籃球社'), (2, '羽球社'), (3, '桌遊社'), (4, '吉他社')], default=0, verbose_name='欲轉社社團')),
            ],
        ),
    ]
