# Generated by Django 3.1.4 on 2022-06-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubitem',
            old_name='advisor',
            new_name='指導老師',
        ),
        migrations.RenameField(
            model_name='clubitem',
            old_name='director',
            new_name='社長',
        ),
    ]
