# Generated by Django 3.1.4 on 2022-06-12 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferform',
            name='club_new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_form', to='log.clubitem', verbose_name='新社團'),
        ),
        migrations.AlterField(
            model_name='transferform',
            name='club_orig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_form', to='log.clubitem', verbose_name='原社團'),
        ),
    ]
