# Generated by Django 3.1.4 on 2022-06-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formitem',
            name='Yes_or_No',
            field=models.BooleanField(default=False, verbose_name='同意轉社'),
        ),
        migrations.AddField(
            model_name='formitem',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='備註'),
        ),
    ]
