# Generated by Django 3.1.4 on 2022-06-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20220603_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubitem',
            name='club_name',
            field=models.CharField(default='資訊社', max_length=8, verbose_name='社團名稱'),
        ),
    ]
