# Generated by Django 3.1.4 on 2022-06-10 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20220610_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferform',
            old_name='user',
            new_name='申請人',
        ),
    ]
