# Generated by Django 3.1.4 on 2022-06-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20220610_2207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormItem',
        ),
        migrations.RenameField(
            model_name='transferform',
            old_name='club_orig',
            new_name='原社團',
        ),
        migrations.RenameField(
            model_name='transferform',
            old_name='club_new',
            new_name='新社團',
        ),
        migrations.AddField(
            model_name='transferform',
            name='note_oa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='指導老師備註'),
        ),
        migrations.AddField(
            model_name='transferform',
            name='note_od',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='社長備註'),
        ),
        migrations.AddField(
            model_name='transferform',
            name='note_stu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='學生備註'),
        ),
        migrations.AlterField(
            model_name='clubitem',
            name='club_name',
            field=models.CharField(default='', max_length=64, verbose_name='社團名稱'),
        ),
    ]
