# Generated by Django 3.1.4 on 2022-06-12 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0003_auto_20220613_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubitem',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_club', to=settings.AUTH_USER_MODEL, verbose_name='指導老師'),
        ),
        migrations.AlterField(
            model_name='clubitem',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_club', to=settings.AUTH_USER_MODEL, verbose_name='社長'),
        ),
    ]
