# Generated by Django 3.1.4 on 2022-06-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20220611_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferform',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='申請時間'),
        ),
    ]
