# Generated by Django 3.1.4 on 2022-06-13 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0004_auto_20220613_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferform',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_list', to=settings.AUTH_USER_MODEL, verbose_name='申請人'),
        ),
    ]
