# Generated by Django 3.1.4 on 2022-06-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_clubitem_stu_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubitem',
            name='stu_name',
        ),
    ]
