# Generated by Django 3.1.4 on 2022-06-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_remove_clubitem_stu_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClubItem',
        ),
    ]
