# Generated by Django 3.1.4 on 2022-06-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0009_clubitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formitem',
            name='stu_name',
            field=models.CharField(default='', max_length=8, verbose_name='學生姓名'),
        ),
    ]
