# Generated by Django 3.1.4 on 2022-06-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0010_auto_20220604_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formitem',
            name='stu_name',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='學生姓名'),
        ),
    ]
