# Generated by Django 3.1.4 on 2022-06-04 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0012_auto_20220604_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubitem',
            name='stu_name',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='log.formitem'),
        ),
    ]
